name: pet_care_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/logo.png
   - assets/brandmark_logo.png
   - assets/profile.png
   - assets/dogs.png
   - assets/veterinarylogo.png
   - assets/grooming_logo.png
   - assets/petstore_logo.png
   - assets/training_logo.png
   - assets/event_image.png
   - assets/community_image.png
   - assets/veterinary_image.png
   - assets/vacations.png
   - assets/operations.png
   - assets/dentistry.png
   - assets/behavioral.png
   - assets/Dr.Anna.png
   - assets/Dr.Vernon.png
   - assets/Dr.Maria.png
   - assets/veterinary_profile.png
   - assets/card1.png
   - assets/card2.png
   - assets/card3.png
   - assets/card4.png
   - assets/card5.png
   - assets/card6.png
   - assets/gromming_profile.png
   - assets/train1.png
   - assets/train2.png
   - assets/train3.png
   - assets/train4.png
   - assets/train5.png
   - assets/shop1.png
   - assets/shop2.png
   - assets/shop3.png
   - assets/shop4.png
   - assets/shop5.png
   - assets/shop6.png





  








